name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.4]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install system dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo mkdir -pm755 /etc/apt/keyrings
        sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
        sudo apt update
        sudo apt install --install-recommends winehq-stable
    - run: npm ci
    - run: npm run build:win --if-present
    - run: mkdir ./product
    - run: find ./dist -mindepth 1 -maxdepth 2 -type f -name '*setup*' -exec cp {} ./product/ \;
    - run: ls -lh
    - name: Build product
      uses: actions/upload-artifact@v4
      with:
        name: product
        path: ./product
